### ISSUE TITLE
Support for Azerty

### ISSUE THREAD

**Issue by DavidDeSloovere** [NTaylorMullen/ShootR#36]

**Comment by NTaylorMullen** [comment]
It'd probably be nice to just add "custom" key bindings and have a few defaults

**Comment by jean-io** [comment]
Space bar does not work with azerty keyboard :8ball:

**Comment by glenthomas** [comment]
My keyboard is qwerty and space bar doesn't work for me either...

**Comment by NTaylorMullen** [comment]
Interesting. I wonder when the shooting mechanic stopped working. Will have to look into it.
